-- MySQL Script generated by MySQL Workbench
-- Tue May  5 11:59:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` DEFAULT CHARACTER SET utf8 ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`country` (
  `idCountry` INT(11) NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`city` (
  `idCity` INT(11) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` INT(11) NOT NULL,
  PRIMARY KEY (`idCity`),
  UNIQUE INDEX `city_UNIQUE` (`city` ASC),
  INDEX `country_idx` (`country` ASC),
  CONSTRAINT `country`
    FOREIGN KEY (`country`)
    REFERENCES `airport`.`country` (`idCountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`airport` (
  `idAirport` INT(11) NOT NULL AUTO_INCREMENT,
  `airport` VARCHAR(45) NOT NULL,
  `city` INT(11) NOT NULL,
  PRIMARY KEY (`idAirport`),
  UNIQUE INDEX `airport_UNIQUE` (`airport` ASC),
  INDEX `city_idx` (`city` ASC),
  CONSTRAINT `city`
    FOREIGN KEY (`city`)
    REFERENCES `airport`.`city` (`idCity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`task` (
  `idTask` INT(11) NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NOT NULL,
  `description` TEXT(200) NULL,
  `dateOfCreation` DATE NOT NULL,
  PRIMARY KEY (`idTask`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`alternative` (
  `idAlternative` INT(11) NOT NULL AUTO_INCREMENT,
  `task` INT(11) NOT NULL,
  `airport` INT(11) NOT NULL,
  PRIMARY KEY (`idAlternative`),
  INDEX `task_idx` (`task` ASC),
  INDEX `airport_idx` (`airport` ASC),
  CONSTRAINT `airport`
    FOREIGN KEY (`airport`)
    REFERENCES `airport`.`airport` (`idAirport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task`
    FOREIGN KEY (`task`)
    REFERENCES `airport`.`task` (`idTask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`role` (
  `idRole` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `role` INT(11) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  INDEX `role_idx` (`role` ASC),
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `airport`.`role` (`idRole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`rating` (
  `idRating` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `expert` INT NOT NULL,
  `alternative` INT NOT NULL,
  `timeOfCreation` DATETIME NOT NULL,
  PRIMARY KEY (`idRating`),
  INDEX `expert_idx` (`expert` ASC),
  INDEX `alternative_idx` (`alternative` ASC),
  CONSTRAINT `expert`
    FOREIGN KEY (`expert`)
    REFERENCES `airport`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `alternative`
    FOREIGN KEY (`alternative`)
    REFERENCES `airport`.`alternative` (`idAlternative`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
