-- MySQL Script generated by MySQL Workbench
-- Sat May 16 19:11:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` DEFAULT CHARACTER SET utf8 ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`country` (
  `id_country` INT(11) NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`city` (
  `id_city` INT(11) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` INT(11) NOT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `country_idx` (`country` ASC),
  CONSTRAINT `country`
    FOREIGN KEY (`country`)
    REFERENCES `airport`.`country` (`id_country`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`airport` (
  `id_airport` INT(11) NOT NULL AUTO_INCREMENT,
  `airport` VARCHAR(45) NOT NULL,
  `city` INT(11) NOT NULL,
  PRIMARY KEY (`id_airport`),
  INDEX `city_idx` (`city` ASC),
  CONSTRAINT `city`
    FOREIGN KEY (`city`)
    REFERENCES `airport`.`city` (`id_city`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`task` (
  `id_task` INT(11) NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `date_of_creation` DATE NOT NULL,
  PRIMARY KEY (`id_task`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`alternative` (
  `id_alternative` INT(11) NOT NULL AUTO_INCREMENT,
  `task` INT(11) NOT NULL,
  `airport` INT(11) NOT NULL,
  PRIMARY KEY (`id_alternative`),
  INDEX `task_idx` (`task` ASC),
  INDEX `airport_idx` (`airport` ASC),
  CONSTRAINT `airport`
    FOREIGN KEY (`airport`)
    REFERENCES `airport`.`airport` (`id_airport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task`
    FOREIGN KEY (`task`)
    REFERENCES `airport`.`task` (`id_task`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`role` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `assessment_task` INT(11) NULL DEFAULT NULL,
  `role` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  INDEX `role_idx` (`role` ASC),
  INDEX `assessment_task_idx` (`assessment_task` ASC),
  CONSTRAINT `assessment_task`
    FOREIGN KEY (`assessment_task`)
    REFERENCES `airport`.`task` (`id_task`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `airport`.`role` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `airport`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`rating` (
  `id_rating` INT(11) NOT NULL AUTO_INCREMENT,
  `rating` INT(11) NOT NULL,
  `expert` INT(11) NOT NULL,
  `alternative` INT(11) NOT NULL,
  `time_of_creation` DATETIME NOT NULL,
  PRIMARY KEY (`id_rating`),
  INDEX `expert_idx` (`expert` ASC),
  INDEX `alternative_idx` (`alternative` ASC),
  CONSTRAINT `alternative`
    FOREIGN KEY (`alternative`)
    REFERENCES `airport`.`alternative` (`id_alternative`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `expert`
    FOREIGN KEY (`expert`)
    REFERENCES `airport`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
